/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface Product {
  'id' : number,
  'sku' : [] | [string],
  'categoryId' : [] | [string],
  'shippingCharge' : [] | [bigint],
  'name' : string,
  'description' : string,
  'fulfillmentType' : string,
  'sellerId' : [] | [string],
  'inventoryCount' : bigint,
  'price' : bigint,
  'taxRate' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], [] | [Category]>,
  'getProduct' : ActorMethod<[number], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProductIdsByCategory' : ActorMethod<[string], Uint32Array>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];