/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'sku' : IDL.Opt(IDL.Text),
  'categoryId' : IDL.Opt(IDL.Text),
  'shippingCharge' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'fulfillmentType' : IDL.Text,
  'sellerId' : IDL.Opt(IDL.Text),
  'inventoryCount' : IDL.Nat,
  'price' : IDL.Nat,
  'taxRate' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listProductIdsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Nat32)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'sku' : IDL.Opt(IDL.Text),
    'categoryId' : IDL.Opt(IDL.Text),
    'shippingCharge' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'fulfillmentType' : IDL.Text,
    'sellerId' : IDL.Opt(IDL.Text),
    'inventoryCount' : IDL.Nat,
    'price' : IDL.Nat,
    'taxRate' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat32], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listProductIdsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Nat32)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };